### ISSUE TITLE
how to use with exist vue project 

### ISSUE THREAD

**Issue by doublenian** [appcomponents/material-components#1]
I see the demo,you have merge the `vue.js`  framework into the` material-components.js` , and `var Vue = VueMaterialComponents.Vue;` , and I worried I can not use it direct into my vue project? So,how can I use it with my exist vue project。 By the way, good job!

**Comment by mjanys** [comment]
Hi, thanks,

I was thinking about that before. Problem is Vue is bundled by webapack as single script ... So I going to refactor this and I'll make Vue as external dependency. It will be more flexible.

Before I do it, try workaround like this:

```
<script src="dist/vue-material-components.min.js"></script>
<script>
var Vue = VueMaterialComponents.Vue
</script>
```

**Comment by doublenian** [comment]
Thanks , I have done with this ,
```
// import Vue from 'vue'
import VueMaterial from '../vendor/material-components/vue-material-components'
var Vue = VueMaterial.Vue;
VueMaterial.registerAll()
``` 
and then use `Vue` normally。

But,This will affect HMR(Hot Reload),so I should refresh page manually.and the reason is [HMR for root change ](https://github.com/vuejs/vueify/issues/25). 

Thanks in advance for refactoring it

**Comment by mjanys** [comment]
Download dist and link as follows:

```
<script src="path/to/Vue 1.0.18+"></script>
<script src="dist/vue-material-components.min.js"></script>
```
