### ISSUE TITLE
vue.common.js warning,and when I use vue-devtools there is error

### ISSUE THREAD

**Issue by doublenian** [appcomponents/material-components#10]
below is my code,I install `material-components` with npm 
```
import Vue from 'vue'

import VueMaterial from 'vue-material-components'
for (const materialComponent in VueMaterial.components) {
  Vue.component(materialComponent, VueMaterial.components[materialComponent])
}
for (const materialDirective in VueMaterial.directives) {
  Vue.component(materialDirective, VueMaterial.directives[materialDirective])
}
// 全局注册mixins
for (const materialMixin in VueMaterial.mixins) {
  Vue.component(materialMixin, VueMaterial.mixins[materialMixin])
}
```
when I use this everything work fine,but with this warning
<img width="1191" alt="2ca78782-e156-474d-8ea5-3276c6bc012e" src="https://cloud.githubusercontent.com/assets/2343611/15241971/daa5d9fc-1925-11e6-8f04-69469771a826.png">

after I use the vue-devtools
<img width="1139" alt="f2348971-9eb9-4dce-bc87-f7c501dd7d20" src="https://cloud.githubusercontent.com/assets/2343611/15241994/fdf4343a-1925-11e6-9987-b1747039e902.png">

there is a error
<img width="1217" alt="645351b6-7292-413a-87d5-1450521d45c5" src="https://cloud.githubusercontent.com/assets/2343611/15242014/135eb30e-1926-11e6-8131-55bc7cf80441.png">

I worried the 'material-components' take the `vue` root scope,thus work not fine

**Comment by mariaczi** [comment]
It is directly connected with #4 
@taylorzane is preparing pull request to cure this issue as it is causing some other issues.

**Comment by mjanzs** [comment]
duplicate
