### ISSUE TITLE
"Module not found: Error: Cannot resolve module 'Vue' " 

### ISSUE THREAD

**Issue by mariaczi** [appcomponents/material-components#12]
Hi, after last PR/merge I have strange issue.
Error shown below. It is shown AFTER build. What's it about?

```
ERROR in ./~/vue-material-components/dist/vue-material-components.js
Module not found: Error: Cannot resolve module 'Vue' in /***/resources/assets/js/ep_panel/node_modules/vue-material-components/dist
 @ ./~/vue-material-components/dist/vue-material-components.js 3:27-41
```

I've already changed plugin usage to:
```
import VueMaterialComponents from 'vue-material-components'
Vue.use(VueMaterialComponents);
```

@mjanys @taylorzane any idea? I cloned repo, installed it and build it (outside of my main project and moved it to my main project `/node_modules/vue-material-components` . (I am not able to `npm run dist` under `myproject/node_modules/vue-material/components` as it is throwing massive errors connected somehow with my project - I am not that deep into npm to understand connection between module under module and rebuild.

EDIT:
Issue is comming from this 
```
if(typeof exports === 'object' && typeof module === 'object')
		module.exports = factory(require("Vue"));
```
which is 3rd line of built file.

**Comment by taylorzane** [comment]
I don't see this as an issue. I did the same exact thing and I don't get any errors. Using your same method, clone repo, build, then `npm i -S /path/to/material-components`. I get a successful build and no issues with running in the browser.

**Comment by mariaczi** [comment]
@taylorzane I managed to build - it was issue with babel 5/6, but even with that, when I am trying to build my main project I am getting this error. Any idea? It is locking me in point..

**Comment by taylorzane** [comment]
I'm unsure. Without looking at your project there isn't much more support I can give. I'm testing with a fully working production application. I'm using babel `6.5.2` and Vue `1.0.21`.

**Comment by mariaczi** [comment]
Hi, it is strange: it is building without errors on Windows ("old" env) but throwing errors on Linux (fresh installation, I moved for ubuntu for dev purposes). Maybe this can give any clue ?

**Comment by taylorzane** [comment]
No that shouldn't matter. All of the packages appear to be JS-only so there shouldn't be any external dependencies. I would check to make sure that all packages are installed for both material-components and your project.

**Comment by mariaczi** [comment]
```
npm cache clean
npm install
``` 
some nodes where missing, but nothing changed, build again - the same error...  on Windows I do not have packaged installed. Does it matter? Damn, this package is really nice, I just started working with these components and again something came up...

**Comment by taylorzane** [comment]
What do you mean by "`packaged installed`"?

**Comment by mariaczi** [comment]
on windows I just have old (not compatinble with Vue.use()) and on linux I've installed vue-material-components through npm.

Do you think I should (Can I?) clean node_modules/vue-material-components from all files, clone git repo into this folder ?

**Comment by taylorzane** [comment]
Yes, you need to be using the same versions of vue-material-components on both environments to ensure that it isn't the environment causing the problem.

**Comment by mariaczi** [comment]
I built it on another machine with windows after clone and install and npm run dist, so there is only some installation/env issue on my linux system. Sorry for that.

**Comment by mariaczi** [comment]
@taylorzane I cleaned all node_modules and made npm install again on my project. Still have the same issue... any idea why? I will appreciate any help

**Comment by mariaczi** [comment]
@taylorzane  are you on Windows/OS/Linux ?
I talked with few colleagues and they all said it is for 99% caused by this issue which is giving warnings on Windows (which we discussed already) and as Windows and OS ignore case it is working, but it will not work on linux...

**Comment by taylorzane** [comment]
I'm running on OS X. I will create a repo that uses Vue.js and this library and post it to Github so that you may test its behavior.

**Comment by mariaczi** [comment]
Will I be able to use it within webpack project? I am afraid not..

**Comment by taylorzane** [comment]
It will be a standalone project using webpack.

**Comment by taylorzane** [comment]
@mariaczi Clone the following repository and run `npm install` and then `npm run dev` and the vue project will be hosted at http://localhost:8080

https://github.com/taylorzane/vuejs-material-components-test

I am using the npm version of this package and I have not run into any issues, except for the error:

```
WARNING in ./~/vue/dist/vue.common.js
There is another module with an equal name when case is ignored.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Rename module if multiple modules are expected or use equal casing if one module is expected.

WARNING in ./~/Vue/dist/vue.common.js
There is another module with an equal name when case is ignored.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Rename module if multiple modules are expected or use equal casing if one module is expected.
```

which is a known issue and does not affect anything (too much) right now.

**Comment by mariaczi** [comment]
It is mistake in webpack export 'vue' :'Vue' where it should be 'vue':'vue'

**Comment by xbill82** [comment]
@taylorzane cloned your test project and ran into the same error after `npm run dev`. @mariaczi what do you mean by "webpack export"?

**Comment by wanyamaman** [comment]
@taylorzane I ran into the same problem as @xbill82 when running your test. Did anyone manage to get a working solution?
