### ISSUE TITLE
md-select: options(list) are not being create properly and in result shown value is wrong

### ISSUE THREAD

**Issue by mariaczi** [appcomponents/material-components#14]
Hello,

I am trying to fork this repo as well, but I can't find solution for this issue which I found and after evaluation I am sure it is about repo not my app.
It is also visible on demo page that despite of select being single or multiple, there is no value shown (with multiple only ' is added for each selected option).

When you will open console and click on the 3rd select, with optgroup you will get:
```
[Vue warn]: Error when evaluating expression "function get() {
	            var _this = this;
	            if (this.value.length) {
	                return this.value.map(function (value) {
	                    return _this.options[value] ? _this.options[value].content : '';
	                }).join(', ');
	            } else {
	                return this.options[this.defaultSelect] ? this.options[this.defaultSelect].content : '';
	            }
	        }". 
vue.js:994 Uncaught TypeError: this.value.map is not a function
```

For first two, options in SelectField are:
```
options: Object
undefined: Object
content: "Option 3"
```

In my project I have the same, even if `createOption` is called as many times as number of objects in my options list, there is still just one option object in the list and content, instead of rendered value is `{{ listElement.label }}`

I was trying to find cause of this issue but I managed only to confirm it, but I haven't found solution so far.

By the way, I think it would be worth to make it possible to pass options as prop, instead of having them in slot with `v-for`.

**Comment by mjanys** [comment]
I did fix for labels
I didn't get error you're talking about. Try it now on http://appcomponents.org/material-components/#!/forms/showcase

if you have still same issue

**Comment by mariaczi** [comment]
@mjanzs I have no idea why, but it is working at DOCS on your website, but it is not working for me.
For single option - it works and value is shown, 
but for multiple there is no value generated... 
I have my selected list initialized in data:
```
selected: []
```
