### ISSUE TITLE
Tab selection indicator has wrong length on window resize

### ISSUE THREAD

**Issue by xXKeyleXx** [appcomponents/material-components#16]
If you resize the browser window the indicator is too short/long
The jQuery version of it works fine.

![long](https://cloud.githubusercontent.com/assets/631504/15507456/f9889c98-21cb-11e6-8cd0-2d0303cab31b.png)
![short](https://cloud.githubusercontent.com/assets/631504/15507458/fa46d06e-21cb-11e6-8d26-07285eafa2ba.png)

**Comment by mjanys** [comment]
fixed

**Comment by xXKeyleXx** [comment]
Thanks
