### ISSUE TITLE
Cannot resolve module 'Vue'

### ISSUE THREAD

**Issue by musicformellons** [appcomponents/material-components#17]
When making bundle with webpack I get:
ERROR in ./~/vue-material-components/dist/vue-material-components.js
Module not found: Error: Cannot resolve module 'Vue' in /home/usr/pq02/node_modules/vue-material-components/dist
 @ ./~/vue-material-components/dist/vue-material-components.js 3:27-41

I am on Ubuntu.

Looks similar to this:
https://github.com/appcomponents/material-components/issues/12

but not really clear to me how it was solved...

**Comment by mjanys** [comment]
Also #4 refers same issue. I haven't got that problem (so it dificult to fix), I did changes based on given instruction in #4. Try it again with code in branch https://github.com/appcomponents/material-components/tree/issue-4-removing-vue-require please

**Comment by mjanzs** [comment]
I've merged branch.
I should helps tell if not
