### ISSUE TITLE
Modal - scope.broadcast is not a function

### ISSUE THREAD

**Issue by goldfinger43** [appcomponents/material-components#19]
Hey,

i try to use the Modalcomponent and get the following error in my console:

Uncaught TypeError: scope.broadcast is not a function

Any other component is working. Im using Vue with Vue-Router, Vue-Ressource and Vue-material-components.
I just copied the code from your Docs for my Modal test. Hope u can help me.

Best regards,
Tino

**Comment by mjanys** [comment]
You are missing mixins.

register them `window.VueMaterialComponents.mixins` by standard way http://vuejs.org/guide/mixins.html

or copy methods from here https://github.com/appcomponents/material-components/blob/master/src/mixins/events/index.ts into your component

**Comment by mjanys** [comment]
Tell if it doesn't work
