### ISSUE TITLE
Uncaught ReferenceError: Vue is not defined

### ISSUE THREAD

**Issue by nor-bu** [appcomponents/material-components#23]
I get this error when i try to use the package
"vue-material-components.js?5247:177 Uncaught ReferenceError: Vue is not defined"

Fresh install with vue-router

Version 0.2.0 works fine

**Comment by mjanzs** [comment]
What exactly are you using ? 

https://github.com/appcomponents/material-components/blob/master/dist/vue-material-components.js#L5049

doesn't have line 5247

**Comment by rizqyhi** [comment]
Hi,
I got the same error when this morning. It was fine when I used this maybe 2 weeks ago.

**Comment by mjanzs** [comment]
Vue was removed as implicit dependency, now vue-material-components.js expect linked script before  vue-material-components. 

You are using it by that way, right ?

**Comment by mariaczi** [comment]
Hi,
right after updating vmc to current version I got the same error! :(
What have you changed? :/
It's crashing totally now.

` vue-material-components.js?5247:177 Uncaught ReferenceError: Vue is not defined `
Can you try to fix it quickly? I was using I think older one or modified by me (for those PR) and it was going nice but now... I made update as you requested in #26 and can't work on my project...

Vue of course is imported long before...

**Comment by mjanzs** [comment]
I went through git log but I found nothing suspicious :(

**Comment by mjanzs** [comment]
I'm still really confused about like 5247 if the script has less lines https://github.com/appcomponents/material-components/blob/master/dist/vue-material-components.js#L5073

**Comment by mjanzs** [comment]
I could be caused by https://github.com/appcomponents/material-components/commit/af99aa3742a41b2fbaa83fe459019baf095f792a#diff-6ca8a73e2455423fb312321d55399ca3

**Comment by mariaczi** [comment]
Could be caused by that you are using stand-alone version and we're using
webpack with vue loader?

sob., 18 cze 2016, 22:27 użytkownik mjanzs <notifications@github.com>
napisał:

**Comment by mjanzs** [comment]
yes, I'm on stand-alone, for me both version are working.

But with require cause some warning in #4 , does anybody know how to manage it ?

**Comment by mariaczi** [comment]
In reality it is leading to line 177:
` exports.BaseComponent = Vue.extend(baseComponent); `

**Comment by mjanzs** [comment]
Yes, I know

problem is that people use different build tools etc.

Stand-alone version has Vue as global variable,
someone had problem with warning if `require` was present, you have problem is `require` is NOT present.

I thinking about

`var VueModule = Vue || require('vue')`

**Comment by mariaczi** [comment]
Please release it all to npm. Last version on npm is from week ago.

niedz., 19 cze 2016, 08:29 użytkownik mjanzs <notifications@github.com>
napisał:

**Comment by mariaczi** [comment]
It's working!

**Comment by mjanzs** [comment]
npm is layer sometimes :) all has been released

**Comment by rizqyhi** [comment]
Yea, it's working now. thanks!
One more thing, did anyone got a warning like this one:
```
./~/vue/dist/vue.common.js
There is another module with an equal name when case is ignored.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Rename module if multiple modules are expected or use equal casing if one module is expected.
```
