### ISSUE TITLE
To handle NAME attribute for FORM elements

### ISSUE THREAD

**Issue by mariaczi** [appcomponents/material-components#26]
Hi,

I just found that it is not handled and all inputs are getting random names which is not ok.
It is quite straight forward by adding name prop and passing it to `<input>` tag, so I did not make PR, but if it is an issue for you I can do it. All other UI libs are implementing that and I think it is crucial as it's making at least autocomplete work fine.

**Comment by mjanzs** [comment]
see http://appcomponents.org/material-components/#!/forms/showcase

```
<md-input name="first_name" :value.sync="firstName" placeholder="Placeholder" success-msg="Success" error-msg="Error"
          :valid="bool(firstNameValid)">
    First Name
</md-input>
```

**Comment by mariaczi** [comment]
Strange.

Vue component:
```
<md-input name="email" :value.sync="loginData.email">
                                Email
                                <template slot="icon-name">email</template>
                            </md-input>
```

Result in DOM:
```
<div class="input-field" name="email">
    <i class="material-icons prefix">
        email
    </i>
    <input class="validate" id="inputfield_0" type="text">
    
    <label for="inputfield_0" class="active">
        
                            Email
                            
    </label>
</div>
```

Why?

**Comment by mjanzs** [comment]
Do you have actual code from master ?

This behaviour is present when component doesn't have property, name in our case. Unresolved property are assigned to root element of component.

**Comment by mariaczi** [comment]
Please release if you can to npm with these updates.
Current 0.2.2 from npm is crashing app with error #23

**Comment by mjanzs** [comment]
done

**Comment by mariaczi** [comment]
Great, but did you find that issue with vue is not defined?
Again - really good library!

sob., 18 cze 2016, 22:07 użytkownik mjanzs <notifications@github.com>
napisał:

**Comment by mjanzs** [comment]
Yes it is reported, but I haven't got project setup with this error, so it is quite hard to figure out the problem without the problem :D

Waiting for response from reporter(s)

**Comment by mariaczi** [comment]
I'll try to update npm in the morning. Maybe it will cure that. It's hard
to reproduce but it's definitely something serious in code as it was
working nice before and quite few people have exactly the same issue now.

sob., 18 cze 2016, 22:13 użytkownik mjanzs <notifications@github.com>
napisał:
