### ISSUE TITLE
To make DISABLED not only css

### ISSUE THREAD

**Issue by mariaczi** [appcomponents/material-components#27]
Hi,

I do not know why you did it that way, that `<md-button disabled>` is giving only disabled CSS when button is still clickable. Could you change it to pass it to both - CSS and button disabled state?

**Comment by mjanzs** [comment]
Reason is `md-button` is realised by `<a>` and this tag hasn't got attribute disabled

**Comment by mjanzs** [comment]
I did `md-btn` component which renders `<button>` and propagates disabled attribute.

`md-button` must stay with `<a>` due backward compatibility

see http://appcomponents.org/material-components/#!/buttons Raised > Stuff button

**Comment by mariaczi** [comment]
Great. Thank you. You're making great progress with this lib last days!
