### ISSUE TITLE
Bower issue

### ISSUE THREAD

**Issue by Alexwijn** [appcomponents/material-components#28]
Hello,

I'm trying to install this package using the following statement in `bower.json`:
```
  "dependencies": {
    "vue-material-components": "https://github.com/appcomponents/material-components.git#~0.3.0"
  }
```

But when bower is done I get only the following files:

- .bower.json
- .gitignore
- bower.json
- demo.html
- LICENSE.txt
- package.json
- README.md
- tsconfig.json

**Comment by mjanzs** [comment]
Can you try it with version `0.3.0`?

**Comment by Alexwijn** [comment]
That did the trick, thanks.
