### ISSUE TITLE
md-circular-preloader

### ISSUE THREAD

**Issue by mariaczi** [appcomponents/material-components#29]
Hi,

It's me again.
I found an issue and hopefully clue for you what's causing that.

Error:
`Unknown custom element: <md-circular-preloader> - did you register the component correctly? For recursive components, make sure to provide the "name" option.`

What I think is causing this issue:
`src\components\circural-preloader` **circural-preloader**
There is misspelling and I think it's not exporting/registering that properly because of that.

Can you take a look and of course - if cured, release to NPM.

**Comment by mjanzs** [comment]
yes, there are typos. I'll fix it
