### ISSUE TITLE
when i use this git repo source code 'demo.html',there is error 'can not find module'

### ISSUE THREAD

**Issue by doublenian** [appcomponents/material-components#6]
this error I find in the source code , so you can reproduce the error。I expect you can fix it ,thank you.By the way, if you fix this problem, mostly problem the issues above will solve.

<img width="818" alt="2ada32a2-9a3b-4a6e-a0cd-65e309e2e2d3" src="https://cloud.githubusercontent.com/assets/2343611/15097480/1666bea0-154f-11e6-99d2-512f121d2458.png">

**Comment by mjanys** [comment]
It is really not reproducible for me. 

commit `SHA-1: b454e94b5f4467b79a2644e7f7d8ae40c4391746` works locally. 

[http://appcomponents.org/material-components/demo.html](http://appcomponents.org/material-components/demo.html) works 
* windows - chrome, edge, IE, firefox
* mac - chrome, safary

Do you have actual code ?

**Comment by mariaczi** [comment]
dist in npm package consists this error. You have to rebuild package and push it again to npm.
There is no this error when you pull file from git

**Comment by doublenian** [comment]
Thanks ,It is work!
